### PR TITLE
feat/Navbar

### PR DESCRIPTION
**Pull request by Tuan980Blue**
Thanh navbar

## Summary by CodeRabbit

- **New Features**
	- Introduced a responsive navigation bar for improved user navigation.
	- Updated footer content to better reflect company services and branding.

- **Improvements**
	- Enhanced user interface with easy access to different sections via the new Navbar.
	- Improved informational value of the footer section, increasing clarity and accessibility.

### CODE REVIEW

**Comment by htilssu** [comment]
@codetitle

**Comment by htilssu** [comment]
@coderabbitai review

**Comment by Tuan980Blue** [comment]
are you oke ?

**Comment by htilssu** [comment]
perfect!!!

**Review by htilssu — APPROVED** [review]

**Pull request merged**
